### ISSUE TITLE
For what reason?

### ISSUE THREAD

**Issue by Garuda-1** [Deletrius366/Advanced_Java_HW#1]
Why do you need an exception which does not override anything?

https://github.com/Deletrius366/Advanced_Java_HW/blob/b049bd19c1690c12a615738ebf8f65935423766f/java-2020/src/ru/ifmo/rain/levashov/walk/WalkerException.java#L3-L7

**Comment by Deletrius366** [comment]
Why exception should override smth? I use it to notify user that my main functions can throw only Walker exceptions instead of IO exceptions
