### ISSUE TITLE
Structure issue

### ISSUE THREAD

**Issue by Garuda-1** [Deletrius366/Advanced_Java_HW#2]
IMHO, ```FileHasher``` is not an appropriate name for a class derived from ```SimpleFileWalker```.

https://github.com/Deletrius366/Advanced_Java_HW/blob/b049bd19c1690c12a615738ebf8f65935423766f/java-2020/src/ru/ifmo/rain/levashov/walk/FileHasher.java#L10

**Comment by Deletrius366** [comment]
OK, FileHasherVisitor
