### ISSUE TITLE
Newline character

### ISSUE THREAD

**Issue by Garuda-1** [Deletrius366/Advanced_Java_HW#3]
How about using ```System.lineSeparator()``` instead of ```'\n'```?

https://github.com/Deletrius366/Advanced_Java_HW/blob/ee425a7d87ab1477a6aa264593605158b5dcae42/java-2020/src/ru/ifmo/rain/levashov/walk/FileHasher.java#L22

**Comment by Deletrius366** [comment]
Fixed
