### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by Garuda-1** [Deletrius366/Advanced_Java_HW#4]
Is it really possible that ```args``` or ```args[i]``` can be null?

https://github.com/Deletrius366/Advanced_Java_HW/blob/ee425a7d87ab1477a6aa264593605158b5dcae42/java-2020/src/ru/ifmo/rain/levashov/walk/RecursiveWalk.java#L11

**Comment by Deletrius366** [comment]
Seems like impossible
