### ISSUE TITLE
No need to catch an exception

### ISSUE THREAD

**Issue by Garuda-1** [Deletrius366/Advanced_Java_HW#6]
As already discussed, method documentation supposes you to throw an exception further, so there is no need to catch it here.

https://github.com/Deletrius366/Advanced_Java_HW/blob/df5a4202d3900f3aa2e8b589035c468b86dcb0de/java-2020/src/ru/ifmo/rain/levashov/arrayset/ArraySet.java#L39-L47

**Comment by Deletrius366** [comment]
Actually yes, but it seems optional as I understand

**Comment by Deletrius366** [comment]
Fixed
