### ISSUE TITLE
Similiar methods

### ISSUE THREAD

**Issue by Garuda-1** [Deletrius366/Advanced_Java_HW#7]
This could be generalized.

https://github.com/Deletrius366/Advanced_Java_HW/blob/df5a4202d3900f3aa2e8b589035c468b86dcb0de/java-2020/src/ru/ifmo/rain/levashov/arrayset/ArraySet.java#L49-L63

**Comment by Deletrius366** [comment]
To be honest, I don't know how to generalize it. Can u help me if u know how?

**Comment by Garuda-1** [comment]
You can add an argument to determine whether look for a lower or higher index. All you need to make dependent on this is to subtract -2 or -1 in (index < 0) branch and move index up or down if not inclusive and equal element presents.

**Comment by Deletrius366** [comment]
Function will be overcomplicated as I see it. Two more branches will make quite big amount of code. 
I see you point, so I drop and try to find solution
